import React,{useEffect,useState}from"react";
import{Alert,KeyboardAvoidingView,Platform,Pressable,ScrollView,Text,TextInput,View}from"react-native";
import{router,useLocalSearchParams}from"expo-router";
import{io as socketIO}from"socket.io-client";
import{api,del,post}from"../../src/api";import{getToken}from"../../src/session";import{Button,C,styles}from"../../src/ui";
const API=(process.env.EXPO_PUBLIC_API_URL||"http://localhost:4000/api").replace(/\/api$/,"/").replace(/\/$/,"");
export default function Chat(){const{id}=useLocalSearchParams<{id:string}>();const[messages,setMessages]=useState<any[]>([]);const[body,setBody]=useState("");const[error,setError]=useState("");const[me,setMe]=useState("");const[typing,setTyping]=useState(false);
async function load(){try{const t=await getToken();const u=await api("/me",{},t||undefined);setMe(u.id);setMessages(await api(`/matches/${id}/messages`,{},t||undefined))}catch(e:any){setError(e.message)}}
useEffect(()=>{let socket:any;let alive=true;(async()=>{const t=await getToken();if(!t||!id)return;socket=socketIO(API,{transports:["websocket"],auth:{token:t}});socket.on("connect",()=>socket.emit("joinMatch",String(id)));socket.on("message.created",(m:any)=>{if(alive&&m.matchId===id)setMessages(v=>v.some(x=>x.id===m.id)?v:[...v,m])});socket.on("typing",(p:any)=>{if(p.userId!==me)setTyping(Boolean(p.isTyping))});await load()})();return()=>{alive=false;if(socket){socket.emit("leaveMatch",String(id));socket.disconnect()}}},[id]);
async function send(){const text=body.trim();if(!text)return;try{const t=await getToken();const m=await post(`/matches/${id}/messages`,{body:text},t||undefined);setMessages(v=>v.some(x=>x.id===m.id)?v:[...v,m]);setBody("")}catch(e:any){setError(e.message)}}
async function unmatch(){Alert.alert("Unmatch","This removes the match and conversation from Bundle.",[ {text:"Cancel",style:"cancel"},{text:"Unmatch",style:"destructive",onPress:async()=>{try{const t=await getToken();await del(`/matches/${id}`,t||undefined);router.back()}catch(e:any){setError(e.message)}}}])}
return <KeyboardAvoidingView style={{flex:1,backgroundColor:C.bg}} behavior={Platform.OS==="ios"?"padding":undefined}><View style={{paddingTop:58,paddingHorizontal:18,paddingBottom:12,borderBottomWidth:1,borderBottomColor:C.line,backgroundColor:C.bg}}><View style={{flexDirection:"row",alignItems:"center",justifyContent:"space-between"}}><Text style={styles.brand}>CONVERSATION</Text><Pressable onPress={unmatch}><Text style={{color:C.danger,fontWeight:"800"}}>Unmatch</Text></Pressable></View>{typing?<Text style={{color:C.muted,marginTop:5}}>Typing…</Text>:null}</View><ScrollView contentContainerStyle={{padding:18,paddingBottom:30}}>{messages.map(m=><View key={m.id} style={{alignItems:m.senderId===me?"flex-end":"flex-start",marginBottom:9}}><View style={{backgroundColor:m.senderId===me?"#2A2112":C.card,borderColor:m.senderId===me?C.accent:C.line,borderWidth:1,borderRadius:18,padding:12,maxWidth:"82%"}}><Text style={{color:C.text,lineHeight:21}}>{m.body}</Text><Text style={{color:C.muted,fontSize:10,marginTop:5}}>{new Date(m.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</Text></View></View>)}{messages.length===0?<Text style={styles.subtitle}>Start the conversation with respect and curiosity.</Text>:null}{error?<Text style={styles.error}>{error}</Text>:null}</ScrollView><View style={{flexDirection:"row",padding:12,borderTopWidth:1,borderTopColor:C.line,backgroundColor:C.card}}><TextInput value={body} onChangeText={(v)=>{setBody(v)}} placeholder="Message" placeholderTextColor={C.muted} maxLength={2000} style={{flex:1,color:C.text,paddingHorizontal:14,paddingVertical:12,borderWidth:1,borderColor:C.line,borderRadius:18,marginRight:8}}/><Pressable onPress={send} style={{justifyContent:"center",paddingHorizontal:14}}><Text style={{color:C.accent,fontWeight:"900"}}>Send</Text></Pressable></View></KeyboardAvoidingView>}
