import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_BUNDLE_API_URL||'http://localhost:4000/api';
const tabs=[['dashboard','Dashboard'],['profiles','Profiles'],['kyc','Identity'],['photos','Photos'],['media','Media'],['reports','Reports'],['deletions','Deletion']];
function Login({onLogin}){const[email,setEmail]=useState('');const[pw,setPw]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(){setBusy(true);setError('');try{const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:pw})});const d=await r.json();if(!r.ok)throw Error(d.error||'Login failed');const me=await fetch(API+'/admin/me',{headers:{Authorization:`Bearer ${d.token}`}});if(!me.ok)throw Error('This account is not authorized for Bundle staff access.');localStorage.setItem('bundle_admin_token',d.token);onLogin(d.token)}catch(e){setError(e.message)}finally{setBusy(false)}}return <main className="auth"><div className="brand">BUNDLE</div><h1>Trust & Safety</h1><p>Secure staff console.</p><div className="card"><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Password<input value={pw} onChange={e=>setPw(e.target.value)} type="password"/></label><button onClick={submit} disabled={busy}>{busy?'Signing in…':'Sign in'}</button>{error&&<div className="error">{error}</div>}</div></main>}
function App(){const[token,setToken]=useState(localStorage.getItem('bundle_admin_token')||'');const[tab,setTab]=useState('dashboard');const[data,setData]=useState({});const[items,setItems]=useState([]);const[error,setError]=useState('');const[role,setRole]=useState('');
 async function call(path,opts={}){const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
 async function loadTab(t=tab){setError('');try{if(t==='dashboard')setData(await call('/admin/dashboard'));else if(t==='profiles')setItems(await call('/admin/profiles'));else if(t==='kyc')setItems(await call('/admin/kyc'));else if(t==='photos')setItems(await call('/admin/photos'));else if(t==='media')setItems(await call('/admin/media'));else if(t==='reports')setItems(await call('/admin/reports'));else if(t==='deletions')setItems(await call('/admin/deletion-requests'));}catch(e){setError(e.message)}}
 useEffect(()=>{if(token){call('/admin/me').then(d=>setRole(d.role)).catch(()=>{localStorage.removeItem('bundle_admin_token');setToken('')})}},[token]);useEffect(()=>{if(token)loadTab(tab)},[tab,token]);
 async function act(path,body){try{await call(path,{method:'POST',body:JSON.stringify(body)});await loadTab()}catch(e){setError(e.message)}}
 const title=useMemo(()=>tabs.find(x=>x[0]===tab)?.[1]||'', [tab]);
 if(!token)return <Login onLogin={setToken}/>;
 return <main><header><div><div className="brand">BUNDLE</div><h1>Trust & Safety</h1><span>{role}</span></div><button className="secondary" onClick={()=>{localStorage.removeItem('bundle_admin_token');setToken('')}}>Sign out</button></header><nav>{tabs.map(([k,label])=><button key={k} className={tab===k?'active secondary':'secondary'} onClick={()=>setTab(k)}>{label}</button>)}</nav>{error&&<div className="error">{error}</div>}{tab==='dashboard'?<Dashboard data={data}/>:<Queue title={title} tab={tab} items={items} act={act}/>}</main>}
function Dashboard({data}){return <><section className="stats">{Object.entries(data).map(([k,v])=><div className="stat" key={k}><b>{String(v)}</b><span>{k.replaceAll('_',' ')}</span></div>)}</section><section className="card"><h2>Operating rule</h2><p>Only verified, approved and actively subscribed members can access discovery, matches and messaging. Verification and moderation decisions are server-enforced.</p></section></>}
function Queue({title,tab,items,act}){return <section><h2>{title}</h2>{items.map(x=><Item key={x.id||x.userId} tab={tab} x={x} act={act}/>)}{items.length===0&&<div className="card"><p>Nothing pending.</p></div>}</section>}
function Item({tab,x,act}){if(tab==='profiles')return <article><div><b>{x.firstName||'Member'}</b><small>{x.city||''} · {x.completeness??0}% complete</small><p>{x.bio||'No bio'}</p></div><div><button onClick={()=>act(`/admin/profile/${x.userId}/review`,{decision:'APPROVED'})}>Approve</button><button className="danger" onClick={()=>act(`/admin/profile/${x.userId}/review`,{decision:'REJECTED',reason:'Please update your profile before resubmitting.'})}>Reject</button></div></article>;
 if(tab==='kyc')return <article><div><b>Identity review</b><small>{x.userId}</small><p>{x.documentType||'Identity document'} · {x.provider||'Provider'}</p></div><div><button onClick={()=>act(`/admin/kyc/${x.userId}/review`,{decision:'VERIFIED'})}>Approve</button><button className="danger" onClick={()=>act(`/admin/kyc/${x.userId}/review`,{decision:'REJECTED',reason:'Verification needs another submission.'})}>Reject</button></div></article>;
 if(tab==='photos')return <article><div><b>{x.user?.profile?.firstName||'Member'} photos</b><small>{x.userId}</small><p>Profile-photo verification pending.</p></div><div><button onClick={()=>act(`/admin/photo/${x.userId}/verify`,{decision:'VERIFIED'})}>Approve</button><button className="danger" onClick={()=>act(`/admin/photo/${x.userId}/verify`,{decision:'REJECTED',reason:'Please update your profile photos.'})}>Reject</button></div></article>;
 if(tab==='media')return <article><div>{x.url&&<img className="thumb" src={x.url}/>}<div><b>{x.user?.profile?.firstName||'Member'} media</b><small>{x.type}</small><p>{x.moderationReason||'Awaiting moderation.'}</p></div></div><div><button onClick={()=>act(`/admin/media/${x.id}/moderate`,{decision:'APPROVED'})}>Approve</button><button className="danger" onClick={()=>act(`/admin/media/${x.id}/moderate`,{decision:'REJECTED',reason:'Image does not meet Bundle media standards.'})}>Reject</button></div></article>;
 if(tab==='reports')return <article><div><b>{x.reason}</b><small>Reported: {x.reportedUser?.profile?.firstName||x.reportedUserId}</small><p>{x.details||'No details supplied.'}</p></div><div><button onClick={()=>act(`/admin/report/${x.id}/resolve`,{status:'RESOLVED'})}>Resolve</button><button className="danger" onClick={()=>act(`/admin/report/${x.id}/resolve`,{status:'RESOLVED',suspendUser:true,note:'Account suspended following safety review.'})}>Suspend</button></div></article>;
 return <article><div><b>Deletion request</b><small>{x.email}</small><p>{x.reason||'No reason supplied.'}</p></div><div><button onClick={()=>act(`/admin/deletion-requests/${x.id}/process`,{decision:'COMPLETED'})}>Process</button><button className="danger" onClick={()=>act(`/admin/deletion-requests/${x.id}/process`,{decision:'REJECTED'})}>Reject</button></div></article>}
createRoot(document.getElementById('root')).render(<App/>);
