import React from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View, ViewStyle } from "react-native";

export const C = { bg:"#08080D", card:"#111119", text:"#F8F7FB", muted:"#9D9AA8", line:"#242431", accent:"#B88A3B", accent2:"#8D63E8", danger:"#E56B76", success:"#57C58A" };
export const styles = StyleSheet.create({
  root:{flex:1,backgroundColor:C.bg,padding:24}, scroll:{padding:24,paddingBottom:60}, brand:{fontSize:14,fontWeight:"800",letterSpacing:3,color:C.accent,textTransform:"uppercase"}, title:{fontSize:34,lineHeight:40,fontWeight:"800",color:C.text,marginTop:10}, subtitle:{fontSize:16,lineHeight:24,color:C.muted,marginTop:10}, card:{backgroundColor:C.card,borderRadius:20,borderWidth:1,borderColor:C.line,padding:18,marginTop:18}, label:{color:C.muted,fontSize:12,fontWeight:"700",textTransform:"uppercase",letterSpacing:1,marginBottom:8}, input:{height:54,borderRadius:14,borderWidth:1,borderColor:C.line,backgroundColor:"#0D0D14",color:C.text,paddingHorizontal:16,fontSize:16,marginBottom:14}, button:{height:54,borderRadius:15,backgroundColor:C.accent,alignItems:"center",justifyContent:"center",paddingHorizontal:18,marginTop:10}, buttonText:{color:"#0B0804",fontSize:16,fontWeight:"800"}, ghost:{height:54,borderRadius:15,borderWidth:1,borderColor:C.line,alignItems:"center",justifyContent:"center",paddingHorizontal:18,marginTop:10}, ghostText:{color:C.text,fontSize:16,fontWeight:"700"}, error:{color:C.danger,fontSize:14,marginTop:10,lineHeight:20}, success:{color:C.success,fontSize:14,marginTop:10,lineHeight:20}, center:{alignItems:"center",justifyContent:"center",flex:1}, pill:{paddingHorizontal:12,paddingVertical:8,borderRadius:999,borderWidth:1,borderColor:C.line,alignSelf:"flex-start"}
});
export function Button({title,onPress,disabled=false,loading=false,ghost=false,style}:{title:string,onPress:()=>void,disabled?:boolean,loading?:boolean,ghost?:boolean,style?:ViewStyle}){return <Pressable disabled={disabled||loading} onPress={onPress} style={[ghost?styles.ghost:styles.button,{opacity:disabled||loading?.5:1},style]}>{loading?<ActivityIndicator color={ghost?C.text:"#0B0804"}/>:<Text style={ghost?styles.ghostText:styles.buttonText}>{title}</Text>}</Pressable>}
export function Field({label,value,onChangeText,placeholder,keyboardType="default",secureTextEntry=false,autoCapitalize="none",multiline=false,numberOfLines}:{label:string,value:string,onChangeText:(v:string)=>void,placeholder?:string,keyboardType?:any,secureTextEntry?:boolean,autoCapitalize?:any,multiline?:boolean,numberOfLines?:number}){return <View><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#5E5B68" keyboardType={keyboardType} secureTextEntry={secureTextEntry} autoCapitalize={autoCapitalize} multiline={multiline} numberOfLines={numberOfLines} textAlignVertical={multiline?"top":"center"} style={[styles.input,multiline&&{height:130,paddingTop:14,paddingBottom:14}]}/></View>}
export function Step({n,label,active=false,done=false}:{n:number,label:string,active?:boolean,done?:boolean}){return <View style={{alignItems:"center",flexDirection:"row",gap:8}}><View style={{width:28,height:28,borderRadius:14,borderWidth:1,borderColor:active?C.accent:done?C.success:C.line,alignItems:"center",justifyContent:"center",backgroundColor:active?"#261D0E":done?"#10231A":"transparent"}}><Text style={{color:active?C.accent:done?C.success:C.muted,fontWeight:"800"}}>{done?"✓":n}</Text></View><Text style={{color:active?C.text:C.muted,fontSize:12,fontWeight:"700"}}>{label}</Text></View>}
